[parsers]
markdown = true

[rules]
orphan-node = "off"

[rules.max-fan-out]
command = "./scripts/max-fan-out.sh"
severity = "warn"

[rules.naming-convention]
command = "./scripts/naming-convention.sh"
severity = "warn"

[rules.required-frontmatter]
command = "./scripts/required-frontmatter.sh"
severity = "warn"

[rules.max-depth]
command = "./scripts/max-depth.sh"
severity = "warn"
