[package]
name = "drft-cli"
version = "0.8.0"
categories = ["command-line-utilities", "development-tools"]
edition = "2024"
homepage = "https://github.com/johnmdonahue/drft-cli"
keywords = ["graph", "linter", "dependency-graph", "structural-integrity"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/johnmdonahue/drft-cli"
description = "A structural integrity checker for linked file systems"

[lib]
name = "drft"
path = "src/lib.rs"

[[bin]]
name = "drft"
path = "src/main.rs"

[dependencies]
anyhow = "1"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
globset = "0.4"
ignore = "0.4"
notify = "7"
notify-debouncer-mini = "0.5"
pulldown-cmark = "0.12"
saphyr = "0.0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "0.8"
url = "2.5.8"

[dev-dependencies]
tempfile = "3"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
